name: argobot
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - xarray
  - aiohttp
  - matplotlib
  - netcdf4
  - seaborn
  - erddapy
  - fsspec
  - gsw
  - pip
  - tqdm
  - cartopy
  - cartopy_offlinedata
  - ipykernel
  - ipywidgets
  - cmocean
  - proplot
  - papermill
  - nbconvert
  - nbformat
  - pip:
      - python-twitter
      - git+https://github.com/euroargodev/argopy