name: Argo Bot
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    name: Tweet Argo Figures
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment-free.yml
          environment-name: argobot

      - name: Execute Notebook and send Tweet
        env:
          TWITTER_SECRET: ${{ secrets.TWITTER_SECRET }}
        shell: bash
        run: |
          conda init bash
          source /home/runner/.bashrc
          conda activate argobot
          papermill floatoftheday.ipynb output.ipynb