name: Argo-bot daily duty
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    name: Tweet Argo Figures
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Install Conda environment
#        uses: mamba-org/provision-with-micromamba@main
#        with:
#          environment-file: environment-free.yml
#          environment-name: argobot
#          cache-env: true

      - name: Set environment variables
        run: |
          echo "CONDA_ENV_FILE=environment-free.yml" >> $GITHUB_ENV
#          echo "PYTHON_VERSION=3.8" >> $GITHUB_ENV

      - name: Setup Micromamba 3.8
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: argobot
          environment-file: ${{ env.CONDA_ENV_FILE }}
          init-shell: bash
          create-args: >-
            python=${{matrix.python-version}}

      - name: Execute Notebook and send Tweet
        env:
          TWITTER_SECRET: ${{ secrets.TWITTER_SECRET }}
        run: |
          python -m ipykernel install --user --name=argobot
          papermill floatoftheday.ipynb output.ipynb
